site_name: Aaron Collins' Projects
theme:
  name: material
  # logo: images/logo512.png
  # favicon: images/favicon.ico
  features:
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - scheme: default
      # primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      # primary: deep purple
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  generator: false # credits to mkdocs-material for generating it
plugins:
  - offline
  - search:
      lang: en
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
nav:
  - Home: index.md
  - Featured Projects:
    - ZeroTier-GUI-Arch: ZeroTier-GUI-Arch.md
    - portableralph: portableralph.md
    - ConnectedDrivingPipelineV4: ConnectedDrivingPipelineV4.md
    - MinecraftDatapackLanguage: MinecraftDatapackLanguage.md
    - projects: projects.md
    - aaron777collins.github.io: aaron777collins.github.io.md
    - ConnectedDrivingMachineLearningPipeline: ConnectedDrivingMachineLearningPipeline.md
    - 2dWebGame: 2dWebGame.md
    - PostAPic: PostAPic.md
    - Control-Windows: Control-Windows.md
    - EasyMLLib: EasyMLLib.md
    - MachineLearningIDE: MachineLearningIDE.md
    - COMP3340Project: COMP3340Project.md
    - sandbox-game-lwjgl: sandbox-game-lwjgl.md
    - opengl-sandbox-game: opengl-sandbox-game.md
  - All Projects:
    - C#:
      - COMP3770A2: COMP3770A2.md
      - comp3770A3: comp3770A3.md
      - dotnet6weatherapp: dotnet6weatherapp.md
      - dotnet7weatherapp: dotnet7weatherapp.md
    - C++:
      - ConnectedDrivingDataGenerator: ConnectedDrivingDataGenerator.md
      - learningcpp: learningcpp.md
    - Go:
      - nvm-windows: nvm-windows.md
    - HTML:
      - ChurchScheduleTemplate: ChurchScheduleTemplate.md
      - ConnectedDrivingMachineLearningPipeline: ConnectedDrivingMachineLearningPipeline.md
      - Deep-Space: Deep-Space.md
      - dwcc-website-snippets: dwcc-website-snippets.md
      - github-slideshow: github-slideshow.md
      - Marking-Assistant: Marking-Assistant.md
      - mermaid-editor: mermaid-editor.md
      - nginx-fancyindex-dark: nginx-fancyindex-dark.md
      - projects-test: projects-test.md
      - smartbudget: smartbudget.md
    - Java:
      - 2DTestGame: 2DTestGame.md
      - Basic-Browser: Basic-Browser.md
      - CampusBookStore: CampusBookStore.md
      - comp4220_A2: comp4220_A2.md
      - Key-Finder: Key-Finder.md
      - Open-World-Zombies: Open-World-Zombies.md
      - opengl-sandbox-game: opengl-sandbox-game.md
      - sandbox-game-lwjgl: sandbox-game-lwjgl.md
    - JavaScript:
      - 2dgametest: 2dgametest.md
      - kibana-extender: kibana-extender.md
      - MessageParser: MessageParser.md
      - urlcron: urlcron.md
      - Using-TLS: Using-TLS.md
      - WebGame: WebGame.md
    - Other:
      - awesome-zerotier: awesome-zerotier.md
      - BetterWorldEdit: BetterWorldEdit.md
      - blackboard-help-clicker: blackboard-help-clicker.md
      - gitconfig-aliases: gitconfig-aliases.md
      - github-upload: github-upload.md
      - markdown-portfolio: markdown-portfolio.md
      - ngx-admin: ngx-admin.md
      - Survival2D: Survival2D.md
      - TerminatorAI: TerminatorAI.md
    - PHP:
      - phpshellterminal: phpshellterminal.md
    - PowerShell:
      - OpenBashInWindowsTerminal: OpenBashInWindowsTerminal.md
    - Python:
      - 2sumsolution: 2sumsolution.md
      - Art-Data-Gatherer: Art-Data-Gatherer.md
      - clawdbotlibrary: clawdbotlibrary.md
      - CompressVideoGUI: CompressVideoGUI.md
      - ConnectedDrivingPipelineV4: ConnectedDrivingPipelineV4.md
      - connecteddrivingresearch: connecteddrivingresearch.md
      - Control-Windows: Control-Windows.md
      - Coupon-Counter: Coupon-Counter.md
      - Distracted-Drving-ML-V3: Distracted-Drving-ML-V3.md
      - DocSearch: DocSearch.md
      - Easy-Math-Substitution: Easy-Math-Substitution.md
      - EasyMLLib: EasyMLLib.md
      - EnhanceAndClick: EnhanceAndClick.md
      - extractembeddedpdftext: extractembeddedpdftext.md
      - FlashGameManager: FlashGameManager.md
      - google-translate-manga-viewer: google-translate-manga-viewer.md
      - live-manga-translator: live-manga-translator.md
      - MachineLearningIDE: MachineLearningIDE.md
      - MinecraftDatapackLanguage: MinecraftDatapackLanguage.md
      - mouse-mover: mouse-mover.md
      - pdf-to-text-ocr: pdf-to-text-ocr.md
      - player-plus-minus-tracker: player-plus-minus-tracker.md
      - PracticeCICDRepo: PracticeCICDRepo.md
      - projects: projects.md
      - python-windowing-test: python-windowing-test.md
      - quicksnip: quicksnip.md
      - simple-ai-game: simple-ai-game.md
      - sophie-mcp: sophie-mcp.md
      - sophie-voice-bridge: sophie-voice-bridge.md
      - StockTraderBotDDDQN: StockTraderBotDDDQN.md
      - vclick: vclick.md
      - word-map-api: word-map-api.md
      - ZeroTier-GUI-Arch: ZeroTier-GUI-Arch.md
    - Racket:
      - COMP4400A4: COMP4400A4.md
      - COMP4400A5: COMP4400A5.md
    - Shell:
      - BashFunctions: BashFunctions.md
      - cddg-docker: cddg-docker.md
      - Fast-Marker: Fast-Marker.md
      - MinecraftPipes: MinecraftPipes.md
      - node-manager: node-manager.md
      - portableralph: portableralph.md
      - SteamDeckPacmanReInstaller: SteamDeckPacmanReInstaller.md
      - tmux-config: tmux-config.md
      - zerotier-flatpaks: zerotier-flatpaks.md
    - TypeScript:
      - 2dWebGame: 2dWebGame.md
      - aaron777collins.github.io: aaron777collins.github.io.md
      - AngularTutorials: AngularTutorials.md
      - BetterPGVectorN8N: BetterPGVectorN8N.md
      - COMP3340Project: COMP3340Project.md
      - GoogleSearchMCP: GoogleSearchMCP.md
      - MCSManager: MCSManager.md
      - openrouterwhitelist: openrouterwhitelist.md
      - PostAPic: PostAPic.md
      - react-playground: react-playground.md
      - RecursiveManager: RecursiveManager.md
    - Vim Script:
      - python3-image.vim: python3-image.vim.md
      - vim-config: vim-config.md
    - mcfunction:
      - BetterFactoryMechanics: BetterFactoryMechanics.md
